#!/usr/bin/env python3
"""Build a valid 128-byte EDID for the ScreenFlip virtual monitor (1920x1080@60,
preferred), with a monitor name containing "Virtual" so the app detects it, and
print it as a C byte array for embedding in Driver.cpp."""

def mfg(code):  # 3-letter PNP id -> 2 big-endian bytes
    a = (ord(code[0]) - 64) & 0x1F
    b = (ord(code[1]) - 64) & 0x1F
    c = (ord(code[2]) - 64) & 0x1F
    v = (a << 10) | (b << 5) | c
    return [(v >> 8) & 0xFF, v & 0xFF]

e = [0] * 128
# Header
e[0:8] = [0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x00]
# Manufacturer "SFP", product 0x5350, serial 1
e[8:10] = mfg("SFP")
e[10], e[11] = 0x50, 0x53            # product code 0x5350 (little-endian)
e[12:16] = [0x01, 0x00, 0x00, 0x00]  # serial
e[16] = 0                            # week
e[17] = 33                           # year 2023 (1990 + 33)
e[18], e[19] = 1, 4                  # EDID 1.4
# Basic display: digital, 8 bpc, DisplayPort; size 51x29 cm; gamma 2.2; features
e[20] = 0xA5
e[21] = 51
e[22] = 29
e[23] = 120                          # gamma (2.2)
e[24] = 0x0A                         # RGB, preferred timing in DTD1
# Chromaticity (generic sRGB-ish)
e[25:35] = [0xEE, 0x91, 0xA3, 0x54, 0x4C, 0x99, 0x26, 0x0F, 0x50, 0x54]
# Established + standard timings: none extra
e[35:38] = [0x00, 0x00, 0x00]
for i in range(38, 54):
    e[i] = 0x01                      # unused standard timing markers

# --- Detailed Timing Descriptor #1: 1920x1080 @ 60 ---
dtd = [0] * 18
pixclk = 14850                       # 148.50 MHz in 10 kHz units
dtd[0] = pixclk & 0xFF
dtd[1] = (pixclk >> 8) & 0xFF
hact, hbl = 1920, 280
vact, vbl = 1080, 45
dtd[2] = hact & 0xFF
dtd[3] = hbl & 0xFF
dtd[4] = ((hact >> 8) << 4) | (hbl >> 8)
dtd[5] = vact & 0xFF
dtd[6] = vbl & 0xFF
dtd[7] = ((vact >> 8) << 4) | (vbl >> 8)
hso, hsw, vso, vsw = 88, 44, 4, 5
dtd[8] = hso & 0xFF
dtd[9] = hsw & 0xFF
dtd[10] = ((vso & 0xF) << 4) | (vsw & 0xF)
dtd[11] = ((hso >> 8) << 6) | ((hsw >> 8) << 4) | ((vso >> 4) << 2) | (vsw >> 4)
himm, vimm = 509, 286
dtd[12] = himm & 0xFF
dtd[13] = vimm & 0xFF
dtd[14] = ((himm >> 8) << 4) | (vimm >> 8)
dtd[15] = 0
dtd[16] = 0
dtd[17] = 0x1E                       # digital separate, +H +V
e[54:72] = dtd

def name_descriptor(text):
    d = [0x00, 0x00, 0x00, 0xFC, 0x00]
    t = (text + " " * 13)[:13]
    d += [ord(c) for c in t]
    if len(t) < 13:
        d[5 + len(t)] = 0x0A
    return d[:18]

def range_descriptor():
    # Monitor range limits 50-75Hz / 30-83kHz / max 170MHz
    return [0x00, 0x00, 0x00, 0xFD, 0x00, 50, 75, 30, 83, 17, 0x00,
            0x0A, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20]

e[72:90] = name_descriptor("SFlip Virtual")
e[90:108] = range_descriptor()
e[108:126] = [0x00] * 18             # empty descriptor
e[126] = 0                           # extension count

# Checksum (byte 127 makes the 128-byte sum a multiple of 256)
e[127] = (256 - (sum(e[:127]) % 256)) % 256

cols = 12
print("// Generated by tools/make_edid.py — 1920x1080@60 ScreenFlip virtual monitor.")
print("static const unsigned char kScreenFlipEdid[128] = {")
for i in range(0, 128, cols):
    row = ", ".join("0x%02X" % b for b in e[i:i + cols])
    print("    " + row + ",")
print("};")
